version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn --workers 4 main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    restart: always
