version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: gunicorn main:app --workers 5 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0
    ports:
      - "8000:8000"
    restart: always
